# Title: Compilation of Media links about the Shiva Sutras
# Description: An acumulation of media to listen to discourses, and video examples
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: indent
# Use
  - Acumulation of links
  - Acumulation of titles
  - Mentioning to what sutra the videos belong to
  - Key points/phrases in each sutra

# Note:
  - So far 1 of the best compilation of videos is SS #83
    
video: Cosmological principle: https://www.instagram.com/reel/CrnKLu2p5QK/?igshid=NTc4MTIwNjQ2YQ==
                               https://www.youtube.com/watch?v=xS_VL-J4pN8

Shiva Sutras Introductions:
   > Note: The video 1 of 'SS #31' (Part 1, 2 and 3) introduces the book

uDev: There is a video where Nithyananda says "Do not go to the highest peak only, go throw the valey also, go throw it sincerely" It is good comparisson with the Android game "Dragon Fly". we should find such video and link both togheter

* Devi Questions
** video A

Satsang by Nithyananda
These 3 parts of the video 1 talk about Anandeshwari attitude (Parvati Vs. Arjuna) The 2 kinds of seekers
Sutra not mentioned

*** Part 1
**** Name: Are You Listening? || Part 1 || Shiva Sutras || 25 Jan 2005
**** Link: https://youtu.be/WvzGLbKiSoc
**** Notes
-
*** Part 2
**** Name: Are You Listening? || Part 2 || Shiva Sutras || 25 Jan 2005
**** Link: https://youtu.be/1A7nWPXIe48
**** Notes
-
*** Part 3
**** Name: Are You Listening? || Part 3 || Shiva Sutras || 25 Jan 2005
**** Link: https://youtu.be/HK0OLuOeKns
**** Notes
-
*** Notes
**** Contents:

** video B

Satsang by Nithyananda
Sutra: uDev

**** Name: What is This Wonder-Filled Universe? || Shiva Sutras || 26 Jan 2005 
**** Link: https://youtu.be/jVGEp239yjE

** video C

Youtube Video with visuals.
Chosen by Seiva D'Arve, when anybody asks "what is this wonderfilled universe" Seiva always remember this Kaleidoscope effect due to his personal experience with it in his satory experience

**** Name: The Splendor of Color Kaleidoscope Video v1.1 Colorful Psychedelic Fractal Flame Visuals to Trip On
**** Link: https://youtu.be/q2fIWB8o-bs
          
* Shiva Sutra #1:
** videos A
   > Part 1: Name: Breathe Into Enlightenment || Part 1 || Shiva Sutras || 23 Feb 2006
           : Link: https://youtu.be/iGI4YnCdlaU
           : Note: - Sutra: mentioned only in sanskrit (confirmed with part 2 that it refers 'SS #1')
                 : - Story of a pandit of shaivism that wanted to teach the king and the king rejected
                 : - When your being ripes, it becomes enlightnement
           > Part 1 (alternative 1): Name: Shiva Sutras -- Book for Direct Experience www.LifeBliss.org	
                                   : Link: https://youtu.be/pBmlvyaCDxw 
                                   : Note: - Sutra: sutra only in sankrit (confirmed it is 'SS #1')
                                   : -
           > Part 1 (alternative 2): Name: Qualityhypnosis.com Shiva Sutras Book for Direct Experience www.LifeBliss.org
                                   : Link: https://youtu.be/zlpTJyrYRh0
                                   : Note: - Sutra:
                                : - (notice the video itself is flipped and mentions: "Shiva Sutra - The ultimate book to give you direct experience" in the introduction)      	   
     Part 2: Name: Breathe Into Enlightenment || Part 2 || Shiva Sutras || 23 Feb 2006
           : Link: https://youtu.be/GHIeYQbP-Rk
           : Note: - Sutra: mentioned at (12:32)
                 : - Content:
                 : - A son tries to revive the father king
           > Part 2 (alternative): Name: Shiva Sutras, The Manual for Enlightenment www.LifBliss.org
                                 : Link: https://youtu.be/hiRdTAam-7s
                                 : Note: - Sutra: sutra only in sankrit (confirmed it is 'SS #1') 
                                 : - Content:
                                 : - Gita: little bit of shastra, stotra, sutra
                                 : - No Sugar coating. No need to use your intelect at all
                                 : - You can't directly catch the seat
   > Part 3: Name: Breathe Into Enlightenment || Part 3 || Shiva Sutras || 23 Feb 2006
           : Link: https://youtu.be/-GwpXC3vxzY
           : Note: - Sutra: 'SS #1' mentioned at (0:14) and (3:00)
                 : Content:
                 : - Mystic vs. Master
                 : - Talk about five elements
                 : - Story about giving cat food to husband
   > Part 4: Name: Breathe Into Enlightenment || Part 4 || Shiva Sutras || 23 Feb 2006
           : Link: https://youtu.be/bpvNZQTDSa4
           : Note: - Sutra:
                 : - 

** video B
      (talvez duplicado)
   > Name: Breath -- Gateway to your Consciousness www.LifeBliss.org
   > Link: https://youtu.be/bkaMIUFCAno
   > Note: - Sutra 'SS #1' mentioned at (2:08)
         : - Sutra 'SS #1' diferent translation at (6:07)
         : Content:
         : - Your breath is under the control of your atman
         : - Just catch the train

** video C
      (talvez duplicado)
   > Name: Watch Your Breath, The Ultimate Technique www.LifeBliss.org
   > Link: https://youtu.be/iyqyVXNqURU
   > Note: - Sutra 'SS #1' at (1:14)
         : - If one technique has to be alive. Nithyananda prescribes this one

 - video 4 (short)------------------------
   > Name: Thinking and Breathing
   > Link: https://youtu.be/tJVnJd7u2JQ

** video D
   > Name: PAPAJI - You are the Emptyness which is here
   > Link: https://youtu.be/JVhrEhiH60w?si=56RhsRWh2OKUueGV
   > Note: Satsang by Papaji
   > Note: According to Seiva, papaji talks about the same Point that happens in our breath, but gives an example not of the breath

* Shiva Sutra #2:
** video 1
   > Name: Beyond Body & Mind Shiva Sutras
   > Link: https://youtu.be/8xk2kgHvWvA
   > Note: All by Nithyananda

** video 2
   > Name: Breath & Mind - Deeper Connections
   > Link: https://youtu.be/iO4jLNpJvcQ
   > Note: - Sutra: mentioned at: (11:07)
         : - 
         : (uDev: I think this video 2 is a short clip of video 1, lets confirm)

* Shiva Sutra #4:
** video 1
   > Name: Find Your Center Deep Within - Shiva Sutras from Nithyananda Videos
   > Link: https://youtu.be/hm8RcYxYQb0
   > Note: All by Nithyananda

** video 2
   > Name: Shiva Sutras Integrate & Evolve ww.LifeBliss.org
   > Link: https://youtu.be/CugnvrUaWac 
   > Note: - Sutra: 'SS #4' mentioned at: (1:20)
         : - Sutra: diferent translation
         
** video 3 (short)
   > Name: The Technique for the Zen Zone www.LifeBliss.org
   > Link: https://youtu.be/E0GOP2E-bVA
   > Note: - Sutra: mentioned at: (0:09)
         : - Sutra: diferent translation
         : Contents: 
         : - You don't even need to practice this technique. All you need to do is to be aware of this technique
         : - How vedas gives 3 steps...
         : -

* Shiva Sutra #5:
** video 1
   > Name: Power of Third Eye (Shiva Sutras)
   > Link: https://youtu.be/swK34bdmuZQ
   > Note: All by Nithyananda

* Shiva Sutra #6:
** video 1
   > Name: Life The Game of Existence - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/U06sgNnFAyE
   > Note: All by Nithyananda

* Shiva Sutra #7:
** video 1
   > Name: Shiva Sutras Death Demystified
   > Link: https://youtu.be/beqUPL4Y2tg
   > Note: satsang by Nithyananda

* Shiva Sutra #8:
** video 1
   > Part 1: Name: Path of Devotion for Transformation www.LifeBliss.org
           : Link: https://youtu.be/3TWmteJV5mM
   > Part 2: Name: Real Master Turns Devotion onto Yourself www.LifeBliss.org
           : Link: https://youtu.be/TRSTJ4pld8E
   > Part 3: Name: Jump into Ultimate from where you are www.LifeBliss.org
           : Link: https://youtu.be/2TryVomeUJY
   > Note  : All by Nithyananda

** video 2
   > Part 1: Name: You are Divinity || Part 1 || Shiva Sutras || 09 March 2006
           : Link: https://youtu.be/Kefi-HGPRbw
   > Part 2: Name: You are Divinity || Part 2 || Shiva Sutras || 09 March 2006 
           : Link: https://youtu.be/g06B8uuY1AU
   > Part 3: Name: You are Divinity || Part 3 || Shiva Sutras || 09 March 2006
           : Link: https://youtu.be/fFqdIn3q9ZM
   > Part 4: Name: You are Divinity || Part 4 || Shiva Sutras || 09 March 2006
           : Link: https://youtu.be/M4VA81I3yG4
   > Part 5: Name: You are Divinity || Part 5 || Shiva Sutras || 09 March 2006
           : Link: https://youtu.be/L6jiyG6nQ-c
   > Part 6: Name: You are Divinity || Part 6 || Shiva Sutras || 09 March 2006
           : Link: https://youtu.be/v0Z_w72bm5Q
   > Part 7: Name: You are Divinity || Part 7 || Shiva Sutras || 09 March 2006
           : Link: https://youtu.be/lCIesCjmCxg
   > Part 8: Name: You are Divinity || Part 8 || Shiva Sutras || 09 March 2006
           : Link: https://youtu.be/Jyqoq7gWzHk
   > Note  : All by Nithyananda
   
* Shiva Sutra #10:
** video 1
   > Name: Live in Your Center to enter into Shiva Consciousness
   > Link: https://youtu.be/Eh8Qh3xzwaE
   > Note: - Sutra: 'SS #10' mentioned at (0:22)
         : - 

* Shiva Sutra #12:
** video 1
   > Name: Shiva Sutras Drop Your Mind and Find Your Center
   > Link: https://youtu.be/_9Uv4eiEWyo
   > Note: satsang by Nithyananda

* Shiva Sutra #15:
** video 1
   > Name: Go Inwards Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/wPOHk69y6FY
   > Note: satsang by Nithyananda
 
* Shiva Sutra #16:
 - video 1 ------------------------------ 
   > Name: From Logic to Love - Shiva Sutras in Nithyananda videos
   > Link: https://youtu.be/aihhsrP8b9Y
   > Note: satsang by Nithyananda
 
* Shiva Sutra #22:
 - video 2 -------------------------------
   > Name: Completion process for health, wealth, relationships and enlightenment
   > Link: https://youtu.be/DJ_ifaTihus
   > Note: - Sutra: not mentioned even it is about the shiva sutras
         : - Sutra: because this is not about the shiva sutras, the video is not the 1st one 

* Shiva Sutra #20:
 - video 1 ------------------------------ 
   > Name: Myth of Hardwork
   > Link: https://youtu.be/CPySadn0h0k
   > Note: satsang by Nithyananda

 - video 2 ------------------------------ 
   > Name: Technique to operate our body from Prana (life force)
   > Link: https://www.youtube.com/watch?v=Xq9KyHXipEU
   > Note: satsang by Nithyananda

 - video 3 ------------------------------ 
   > Name: Toy Story 2 - Introducing Sheriff Woody!
   > Link: https://www.youtube.com/watch?v=wbkojrVKj-s 
   > Note: Jessie introduces woody at toy story
 
* Shiva Sutra #23:
 - video 1 ------------------------------ 
   > Name: Deeper Understandings from teachings of Shiva
   > Link: https://youtu.be/IGo0QEYVSQM
   > Note: satsang by Nithyananda

* Shiva Sutra #24:
** video 1
   > Part 1: Name: Sophistication Causes Depression! || Part 1 || Shiva Sutras || 21 March 2007
           : Link: https://youtu.be/F86USewvA88
   > Part 2: Name: Do Not Miss The Master! || Part 2 || Shiva Sutras || 21 March 2007
           : Link: https://youtu.be/ciGAXLTF46k
   > Part 3: Name: Solve Your Problems || Part 3 || Shiva Sutras || 21 March 2007
           : Link: https://youtu.be/Knm1JOjwSqE
   > Part 4: Name: Honest Anger, Not Pseudo Anger! || Part 4 || Shiva Sutras || 21 March 2007
           : Link: https://youtu.be/jA649kAaCz4
   > Part 5: Name: Are You Empty Or Fulfilled || Part 5 || Shiva Sutras || 21 March 2007
           : Link: https://youtu.be/MzTWamVCvOQ
   > Part 6: Name: Automatic Visualisations! || Part 6 || Shiva Sutras || 21 March 2007
           : Link: https://youtu.be/dXHnkmkq2Ok
   > Part 7: Name: Powerful Meditation To Relieve Anger || Part 7 || Shiva Sutras || 21 May 2007
           : Link: https://youtu.be/h54hNRpu1qE
 
* Shiva Sutra #25:
** video 1
   > Name: Capitalize Your Energy - Shiva Sutras
   > Link: https://www.youtube.com/watch?v=eq0V-seTR2I
   > Sutra: Mentioned SS#25 at: 3:09
   > Note: satsang by Nithyananda
   > Note: It shows something about the religion  of Jesus: "I am That" is said on the old testment. Here in this video, It is said that one Maha Vakya is "Tatvamasi" or "You are That" (mentioned at 4:40) and there were disciples enlightened only with this
* Shiva Sutra #26:
** video 1
   > Name: Meditation Technique to Unclutch® from Your Mind
   > Link: https://youtu.be/dQGzzkNyG_E
   > Note: satsang by Nithyananda
 
* Shiva Sutra #28:
** video 1
   > Name: You Have Innate Intelligence
   > Link: https://youtu.be/ouo1k3mtJRA
   > Note: satsang by Nithyananda

* Shiva Sutra #30:
** video 1
   > Part 1: Name: The Truth About Brahmacharya || Part 1 || Shiva Sutras || 28 April 2006
           : Link: https://youtu.be/dSB7kkufM_Y
   > Part 2: Name: The Truth About Brahmacharya || Part 2 || Shiva Sutras || 28 April 2006
           : Link: https://youtu.be/lNFbT-17mO0
   > Part 3: Name: The Truth About Brahmacharya || Part 3 || Shiva Sutras || 28 April 2006
           : Link: https://youtu.be/foIkmqYp0zE
 
* Shiva Sutra #31:
** video 1
   > Part 1: Name: Book with No Introduction || Part 1 || Shiva Sutras || 13 July 2006
           : Link: https://youtu.be/5mxCV8s9Mo4
           : Note: - Sutra: not mentioned
                 : - Content:
                 : - Introdution the book with no introductions
                 : - We do not know if Shiva really wrote this book. But who is ever able to write this book, stays in shiva consciousness
                 : - Shiva goes straight to the point, not waisting any single word
   > Part 2: Name: The Relationship between Shiva & Devi || Part 2 || Shiva Sutras || 13 Jul 2006
           : Link: https://youtu.be/qv7fVLwiOc8
           : Note: - Sutra: not mentioned
                 : - Content:
                 : - Shiva does not need to give introduction to Devi
                 : - "Battle" of 2 seekers with a garland of flowers
                 : - Body is the income source for doctors, mind is the income source for "Philosophers"
                 : - Nithyananda explains why Shiva enters directly into the sutras
   > Part 3: Name: 10,000 Year Old Book || Part 3 || Shiva Sutras || 13 Jul 2006
           : Link: https://youtu.be/tB02zCXn7Qw
           : Note: - Sutra: mentioned at: (15:05) 
                 : - Content:
                 : - Shiva does not need to use more words because Devi does not need to be convinced (Shiva has no vested interest)
                 : - Explanation of Maya
   > Part 4: Name: Peace in Your Consciousness || Part 4 || Shiva Sutras || 13 Jul 2006
           : Link: https://youtu.be/7wBCBxcyjFs
           : Note: - Sutra: not mentioned
                 : - Content:
                 : - When you see a person, you reduce the person to an object
                 : - What ever exists is energy, whatever exists is GOD
                 : - Do not push your problems to the unconscious, push them to superconscienceness
                 : - You do not use all parts in your house
                 : - "Pravrity" Vs. "Nivrithy" (Words not written/spelled correctly)
   > Part 5: Name: The Power of Words || Part 5 || Shiva Sutras || 13 July 2006
           : Link: https://youtu.be/Ze_y_2M6TFY
           : Note: - Sutra: 'SS #31' mentioned at: (10:25)
                 : - Content:
                 : - Do not push your problems to the unconscious, push them to superconscienceness
                 : - When you see a person, you reduce the person to an object
   > Part 6: Name: Raise Yourself towards Superconsciousness || Part 6 || Shiva Sutras || 13 July 2006
           : Link: https://youtu.be/gW0FsGhFYkM
           : Note: - Sutra: not mentioned
                 : - Content:
                 : - This part explains "advaita"
   > Note  : satsang by Nithyananda

* Shiva Sutra #33:
** video 1
   > Part 1: Name: From Shava to Shiva - Shiva Sutras in Nithyananda videos
             Link: https://youtu.be/U-VP7faHNoM
   > Part 2: Name: Experience the Cosmic Space - Technique & Meditation
           : Link: https://youtu.be/oSzqo1pM9FI
   > Part 3: Name: Experience The Wholeness
           : Link: https://youtu.be/M7aRpdTRxpY
   > Note  : satsang by Nithyananda

* Shiva Sutra #34:
** video 1
   > Part 1: Name: Shiva Sutra || Part 1|| Satsang || 29 Mar 2007
           : Link: https://youtu.be/maJXebzVek0
           : Note: - Sutra:
                 : -
   > Part 2: Name: Shiva Sutra || Part 2 || Satsang || 29 Mar 2007
           : Link: https://youtu.be/cRbUcRVWYNw
           : Note: - Sutra:
                 : - 
   > Part 3: Name: Shiva Sutra || Part 3 || Satsang || 29 Mar 2007
           : Link: https://youtu.be/-QUXJi872Tc
           : Note: - Sutra:
                 : -
   > Part 4: Name: Shiva Sutra || Part 4 || Satsang || 29 Mar 2007
           : Link: https://youtu.be/okWiw353SVI
           : Note: - Sutra:
                 : - 
   > Part 5: Name: Shiva Sutra || Part 5 || Satsang || 29 Mar 2007
           : Link: https://youtu.be/Psh3L5zWFwk
           : Note: - Sutra:
                 : - 
   > Part 6: Name: Shiva Sutra || Part 6 || Satsang || 29 Mar 2007
           : Link: https://youtu.be/RI2Bnr8WH40
           : Note: - Sutra: 'SS #34' mentioned at (0:15)
                 : - 
 
* Shiva Sutra #35:
** video 1
   > Name: Shiva Sutras - Solutions for a Sophisticated Society
   > Link: https://youtu.be/jpziOnyWjwg
   > Note: satsang by Nithyananda
   > Content: Explains how many sutras are there and where Vigyan Bhairav Tantra is inserted

** video 2
   > Name: Dissolution of the Mind
   > Link: https://youtu.be/xcwC_f2JUw8 
   > Note: satsang by Nithyananda
 
* Shiva Sutra #37
** Video A
- All by Nithyananda

*** Part 1
**** Name: Truths about Inner Chattering
**** Link: https://youtu.be/lXzaWgSKLEA
**** Notes
- The video does not mention the sutra, but in the next video (Part 2) we understand it is the continuation of this one

*** Part 2
**** Name: Going from Words to Wordlessness
**** Link: https://youtu.be/dPko9iXUjqQ?si=sCn7_S7t26yv_J5_
**** Notes
- Sutra mentioned at 19:35
  
*** Part 3
**** From Sounds to Silence - Technique & Meditation
**** link: https://youtu.be/rJk-gJ_YIs0
**** Notes
- This video happens after de diacourse to practice. The sutra em partially mentioned at different timestamps because of that
- Sutra 'SS #37' mentioned partially at: (13:37) and (18:01) and (26:01)
* Shiva Sutra #38:
SS#38:
 > Bathe in the center of sound, As in the continuous sound of a waterfall. Or, by putting the fingers in the ears, Hear the sound of sounds.

SS#38 (given by Nithyananda):
 > Bathe in the center of sound, As in the continuous sound of a waterfall. Or, by putting the fingers in the ears, Hear the sound of sounds (Anahata Dhwani).

** video 1 (by Nithyananda)
*** Part 1: Name: Silence Within || Part 1 || Shiva Sutras || 25 May 2007
            : Link: https://youtu.be/4H0sa9m9EpA
            : SS#38 mentioned at: 10:25

            : "All great scriptures agree on one point: From sound the whole universe originated"
            : "Anahata Dhwani" uncreated sound
            : This video has a story of a boat and water gushing

*** Part 2: Name: Silence Within || Part 2 || Shiva Sutras || 25 May 2007
            : Link: https://youtu.be/Id8EqNKoOKI

*** Part 3: Name: Silence Within || Part 3 || Shiva Sutras || 25 May 2007
            : Link: https://youtu.be/i2M7V_1_s7s" 

*** Part 4: Name: Silence Within || Part 4 || Shiva Sutras || 25 May 2007
            : Link: https://youtu.be/IYJLZvV1uKs

*** Part 5: Name: Silence Within || Part 5 || Shiva Sutras || 25 May 2007
            : Link: https://youtu.be/Z0MjAfJnLwo
            : SS#38 mentioned at 7:16

            : "Pratyahara" Widrawling
            : "Dharana" centering (to get in the center)

*** Part 6: Name: Silence Within || Part 6 || Shiva Sutras || 25 May 2007
            : Link: https://youtu.be/z_Jg0vjfmFA

** video 2 (by Nithyananda)
   > Part 1: Name: Enter Into The Centre Of Silence || Part 1 || Shiva Sutra || 25 May 2007
           : Link: https://youtu.be/LcM4RWYSGkk
           : Note: - Sutra: 'SS #38' mentioned at: (9:30)
                 : - Sutra: Diferent translation
   > Part 2: Name: Force with Independent Intelligence Is Power || Part 2 || Shiva Sutras || 25 May 2007
           : Link: https://youtu.be/0kEXcRS1YyE
           : Note: - Sutra: mentioned at: 8:10~
                 : - 
   > Part 3: Name: Are You A Suffering Receiving Station? || Part 3 || Shiva Sutras || 25 May 2007
           : Link: https://youtu.be/uF_7UfdVJDY
           : Note: - Sutra:
                 : -
   > Part 4: Name: Suffering Comes From Resistance || Part 4 || Shiva Sutras || 25 May 2007
           : Link: https://youtu.be/2zPkR22Wvx8
           : Note: - Sutra:
                 : - 
   > Part 5: Name: Intense Silence is The Silence of Mahadeva || Part 5 || Shiva Sutras || 25 May 2007
           : Link: https://youtu.be/C0cHEHhqvj0
           : Note: - Sutra: mentioned at (1:15)
                 : - 
   > Note  : in 'SS #38' video 1 and video 2 are same videos but with diferent edits

** video 3 (by Nithyananda)(short)
   > Name: What Is The Meaning Of A Mantra || Shiva Sutras || 25 May 2007
   > Link: https://youtu.be/o9lpfJlHQxc

*** Notes
Mantras don't have any meaning
 
* Shiva Sutra #39:
** video 1
   > Name: Power of Sound Shiva Sutras Nithyananda Videos
   > Link: https://youtu.be/upAHU4y0Pi0
   > Note: - Sutra: 
   > Note: satsang by Nithyananda
 
* Shiva Sutra #40:
** video 1
   > Name: Krishnabai & Jai Sahaja! – He Mata Kali
   > Link: https://youtu.be/i7B4SspgC0w
   > Note: - It is an example of people practicing
         : - It is a Bajhan music from youtube
 
** video 2
   > Part 1: Name: What is Seeking?
           : Link: https://youtu.be/gk0dbQCc2B8 
   > Part 2: Name: Richness of Vedic Tradition
           : Link: https://youtu.be/tsW5kvKoM0g
           : Note: Does not mention the sutra
   > Part 3: Name: Integrate Yourself for Superconscious Experience to happen
           : Link: https://youtu.be/Ji0j93bAuDo 
   > Part 4: Name: Deep Awareness to Sound Technique and Meditation
           : Link: https://youtu.be/QT9eGZiq9Xs 
           : Note: Diferent translation 
                 : Video with a guided meditation
   > Note  : all by Nithyananda

** video 3
   > Part 1: Name: Knowledge Should Be Free || Part 1 || Shiva Sutras || 18 April 2007
           : Link: https://youtu.be/9dnvfZqnF2I
   > Part 2: Name: Create The Best Inner Software || Part 2 || Shiva Sutras || 18 April 2007
           : Link: https://youtu.be/conXY3Wgw74
   > Part 3: Name: Humans Are Unique, Not Equal! || Part 3 || Shiva Sutras || 18 April 2007
           : Link: https://youtu.be/Ikl2sWmkyFg
           : Note: First one to mention the sutra
      falta ouvir:
      muito parecido com o video 2, é preciso perceber a diferenca
   > Part 4: Name: Jeeva, Jagat, Ishwara || Part 4 || Shiva Sutras || 18 April 2007
           : Link: https://youtu.be/SUSuxcMh_aA
   > Part 5: Name: Sound Meditation || Part 5 || Shiva Sutras || 18 April 2007
           : Link: https://youtu.be/gN00wsiKRIE
 
* Shiva Sutra #41:
** video 1
   > Name: Music Avenue to Awareness - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/CgcGNZ0V1kM
   > Note: satsang by Nithyananda
 
* Shiva Sutra #44:
** video 1 (by Nithyananda)
   > Part 1: Name: Centered on Soundlessness
           : Link: https://youtu.be/bukg6qtVtso
           > Note: - Sutra: not mentioned properly. But gives no doubt about the sutra
                 : - Sutra: kind of mentioned at (0:13) and (9:25)
                 : (satsang by Nithyananda)
                 : Contents:
                 : - Shiva says "Let you become me". Or, "Let you achieve the state of Shiva"
                 : - 1 Brahamachay = 150 monkeys
                 : - Talks about zen koans (sound of one hand clapping)
                 : - Anahata vs. Ahata

                 : Vishnu means: All Pervasive
                 : Shiva means: Auspiciousness
   > Part 2: Name: Omkara Meditation -- The First, Last & Ultimate Sound
           : Link: https://youtu.be/ZBVO8KeGmHg
           : Note: - Sutra: not mentioned properly
   > Note  : - Same description on these videos: 'This clip is taken from discourse titled, "Sensitivity with Sound"' 
           : - Same technique given by Sadhguru. When chanting, center your attention into the vibration it creates instead of the sound it creates

* Shiva Sutra #45:
** video 1
   > Name: Enter the Space that can never Die Technique & Meditation
   > Link: https://youtu.be/wPSELw0cOXY
   > Note: satsang by Nithyananda
 
* Shiva Sutra #46:
** video 1
   > Part 1: Name: Everything in Life is Auspicious || Part 1 || Shiva Sutras || 2 May 2007
           : Link: https://youtu.be/CDfzUyvQftI
           : Note: - Sutra:
                   - Nithyananda says that this is the sutra 46 (marches with this Seiva's list aquired from the internet)
                   - Youtube comments: Name Of The Program: Shiva Sutras - Technique of Sound Part 1
   > Part 2: Name: Be in Present Moment to Conquer Death || Part 2 || Shiva Sutras || 2 May 2007
           : Link: https://youtu.be/y6eVJg0dnxk
           : Note: - Sutra:
                 : - Youtube comments mentions the part 1 link 
   > Part 3: Name: Kundalini Awakening || Part 3 || Shiva Sutras || 2 May 2007
           : Link: https://youtu.be/HHY-TFUBRFU
           : Note: - Sutra:
   > Part 4: Name: Kundalini Awakening || Part 4 || Shiva Sutras || 2 May 2007
           : Link: https://youtu.be/Q9xhq2KuRm0
           : Note: - Sutra:
   > Note: satsang by Nithyananda
** Video 2

Satsang by Nithyananda

Name: Awakening the Kundalini Shakti
Link: https://www.youtube.com/watch?v=Ghrq8e_LIos&t=1106s or https://youtu.be/Ghrq8e_LIos?si=VeAGOxNkR-bCwLsc
Note: - 'SS #46' mentioned at: 13:11
      
* Shiva Sutra #55:
** video 1
   > Name: Shiva Sutras The How to Enlightenment Nithyananda
   > Link: https://youtu.be/WnFmqpEXRto
   > Note: satsang by Nithyananda

** video 2
   > Part 1: Name: Tune into Bliss || Part 1 || Shiva Sutras || 10 May 2007
           : Link: https://youtu.be/S2IHvttN3ps
	   : Short video: Name: Shiva -- The Master of Masters www.LifeBliss.org
	     	   	: Link: https://youtu.be/FKYlqOrMqFQ
			: - Shiva is jagat guru and works with energy while patanjali works with morality based people.
   > Part 2: Name: Tune into Bliss || Part 2 || Shiva Sutras || 10 May 2007
           : Link: https://youtu.be/Ta2AVVREzjA
   > Part 3: Name: Tune into Bliss || Part 3 || Shiva Sutras || 10 May 2007
           : Link: https://youtu.be/MCmCJfH7d8I 
           : Note: He speaks about Jesus
   > Part 4: Name: Tune into Bliss || Part 4 || Shiva Sutras || 10 May 2007
           : Link: https://youtu.be/swaNsi0ERh8
   > Part 5: Name: Tune into Bliss || Part 5 || Shiva Sutras || 10 May 2007
           : Link: https://youtu.be/h1hl4F9CQUU 
   > Note  : satsang by Nithyananda

** video 3
   > Name: Achieve Extraordinary Powers Through This Breathing Process | Do This for 21 Days Before Sleep
   > Link: https://youtu.be/0Y5WsdNqpDo
   > Note: - Sutra
         : - Let my breathing pattern become the cosmic breathing pattern
         : - This way you are every night surrendering into mahadeva's lap (if you need me to wake up, wake me up... and let me wake up wiyh all the qualities you want me to have)

** video 4
   > Name: https://www.youtube.com/watch?v=CDnW4D_a2vw
   > Link: https://youtu.be/CDnW4D_a2vw
   > Note: - Sutra: not mentioned
         : - Yoga Nidra (to fall asleep. Nidra means "sleep") 

* Shiva Sutra #56:
** video 1
   > Name: Move Into Deeper Consciousness - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/2fQMKTLDhUM 
   > Note: - Sutra: 'SS #56' mentioned at: (11:27)
         : - NN talks about Maya
         : - Has a diferent translation
   > Note: How to practice according to Nythiananda: Put your attention twoards the seer, not towards the acene
            
* Shiva Sutra #58:
** video 1
   > Name: Paramahansa Yogananda: On the Dream-Nature of the World
   > Link: https://youtu.be/GQQR9Fg128E
   > Note: by Paramahamsa Yogananda
 
* Shiva Sutra #59:
** video 1
   > Name: Be Authentic with Your Emotions
   > Link: https://youtu.be/GXfd9x0yw0E
   > Note: satsang by Nithyananda
         : The video does not mention the sutra
 
* Shiva Sutra #60:
** video 1
   > Part 1: Name: Science of Life and Seeking
           : Link: https://youtu.be/f3MX-Q0vxyA
   > Part 2: Name: Sound of Prana - The subtlest mantra versus Mantra Chanting
           : Link: https://youtu.be/WqZJKynQWz0
   > Part 3: Name: Enlightenment Comes with Responsibility
           : Link: https://youtu.be/7RmBR-344I0
   > Part 4: Name: Surrender - Living Master vs. Dead Master vs Deity
           : Link: https://youtu.be/jd7dtA_9iRE
   > Part 5.1: Name: Acceptance To Transformation || Part 5.1 || Shiva Sutras || 13 Nov 2007
             : Link: https://youtu.be/ssiCKZGw2fo
             : Note: - Sutra: (the first one to mention the sutra)
                   : -  
      falta ouvir:
   > Part 5.2: Name: Acceptance to Transformation || Part 5.2 || Shiva Sutras || 13 Nov 2007
             : Link: https://youtu.be/rXo0eZuMg38
   > Part 5.3: Name: Acceptance To Transformation || Part 5.3 || Shiva Sutras || 13 Nov 2007
             : Link: https://youtu.be/d4aFxSCYmLo
   > Part 6: Name: How To Accept & Influence Change || Part 6 || Shiva Sutras || 13 Nov 2007
           : Link: https://youtu.be/DZFVZl2fJ5s
   > Part 7: Name: Can Money Buy Happiness? || Part 7 || Shiva Sutras || 13 Nov 2007
           : Link: https://youtu.be/T16Po5-fiYk
   > Part 8: Name: Developing Devotion To The Divine || Part 8 || Shiva Sutras || 13 Nov 2007
           : Link: https://youtu.be/O8IS1Pdmnao
           : Note: This video is the one that gives all the links in it's description
   > Part 9: Name: Technique and Meditation: You are Emptiness
           : Link: https://youtu.be/qXLOeuXDHHo
   > Note  : satsang by Nithyananda

* Shiva Sutra #61:
** video 1
   > Name: You are Emptiness
   > Link: https://youtu.be/WSogwYCUKiQ
   > Note: - Sutra 'SS #61' mentioned at (0:28)
         : - 

* Shiva Sutra #63:
** video 1
   > Name: Technique for Sudden Enlightenment by being Uninterruptedly Aware
   > Link:and 64: https://youtu.be/1XGUxEciWws
   > Note: satsang by Nithyananda

SS 67
https://youtube.com/shorts/V6F7WrWK-sk?feature=share
https://youtube.com/shorts/FSuYZadqAtg?feature=share
by Sadhguru
 
* Shiva Sutra #69:
** video 1
   > Name: Beyond Freedom and Bondage - Shiva Sutras
   > Link: https://youtu.be/wbVZsgLVQiM
   > Note: satsang by Nithyananda
 
* Shiva Sutra #70:
** video 1
   > Part 1: Name: Dhyana Sutra
           : Link: https://youtu.be/R56i872WaPo
   > Part 2: Name: Meditation Technique to give Intensity
           : Link: https://youtu.be/WeQJHUfRb44
   > Note  : satsang by Nithyananda

* Shiva Sutra #71:
** video 1
   > Part 1: Name: Right Listening
           : Link: https://youtu.be/oKY8f_PleA4
           : - Sutra: not mentioned
           : Note: Does not mention the sutra
                 : - First buda discourse and last buda discourse are same
   > Part 2: Name: 'Light' As Life Energy Question & Answers
           : Link: https://youtu.be/7Ura8ll_lYk
           : Note: Sutra not mentioned
                 : This video is Q & A, and one of the questions are about 'SS #69' at: (4:34)
   > Part 3: Name: 'Light' As Life Energy
           : Link: https://youtu.be/e0v1cVIQqt4
           : Note: Sutra: 'SS #71' mentioned at: (0:20)
                 : There was a story in the bible where this happened to Jesus
                 : - Story where food was full of ants 
   > Notes : Youtube video description: 'In this clip taken from discourse titled " Experience the life energy in you"'

** video 2
   > Name: Jesus Animation Video - The Woman Who Touched
   > Link: https://youtu.be/4kHDMTLBRbc
   > Note: - Video ilustrating A woman Touching Jesus

* Shiva Sutra #72:
** video 1
   > Name: Grow with Sensitivity - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/gWQyJHiT9js
   > Note: satsang by Nithyananda
   Sutra: 'SS #72' mentioned at: (1:34)
   - How nithyananda got enlightened

** video 2
   > Name: There is neither you nor me
   > Link: https://youtu.be/BzeC7HZ740c
   > Note: - Sutra: 'SS #72' mentioned at: (0:21)
         : - 
         : Contents
         : - Mentions "Dvandva" which is the term used to describe pairs of polar opposites
         : - Mentions how NN felt at the moment of enlightenment
         : - Prana Pratishtha is mentioned by Nithyananda and it looks similar to giving the breath of life
         :   (if it mentions prana pratishtha, then it is similar to "sacramento da crisma" in Jesus religion where Bishops try to place their thumb in children's forehead simulating prana prathishta)
         :   (uDev: find in the bible where such practices of bishops are taking place)
         : - Mentions Aura
         : - He sais that next sutra is meant to experience same thing but at particular point in the day, at: (7:16)
         : - Nithya Sutra
         :
         : (uDev: I think it is a short video from video 1)
         
* Shiva Sutra #73:
** video 1
   > Name: Grow with Sensitivity - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/gWQyJHiT9js (59:00)
   > Note: - Sutra: 
         : Contents:
         : - NN sais in 'SS #72' video 2 that this one sutra 'SS #73' is Dhyana Sutra (both are same method but this one is to practice at a prticula time)
   > Note: satsang by Nithyananda

* Shiva Sutra #76:
** video 1
   > Name: Meditating on Darkness
   > Link: https://youtu.be/NO0oejD4vJs
   > Note: - Sutra: 'SS 76' mentioned at: (5:27) and (12:02)
         : - Sutra: 'SS 77' mentioned at: (12:55)
         : - Same video as video 1 of 'SS 77'
         : - NN sais: it'sFor sharp eyes
         : - NN explains why deities are craved in dark granite (like the shiva linga)
         : - To experience the same state that you are experiencing in the deep sleep, but with consciousness
         : - For restfull awareness

* Shiva Sutra #77:
** video 1
   > Name: Meditating on Darkness
   > Link: https://youtu.be/NO0oejD4vJs
   > Note: - Sutra: 'SS 76' mentioned at: (5:27) and (12:02)
         : - Sutra: 'SS 77' mentioned at: (12:55)
         : - Same video as video 1 of 'SS 76'
         : - NN sais: it'sFor sharp eyes
         : - NN explains why deities are craved in dark granite (like the shiva linga)
         : - To experience the same state that you are experiencing in the deep sleep, but with consciousness
         : - For restfull awareness

* Shiva Sutra #78:
** video 1
   > Name: Meditation Technique to Radiate Love and Attitude Change
   > Link: https://youtu.be/hK4l0pWIkck
   > Note: - Sutra: 'SS #78' mentioned at (11:30)
         : - 
 
* Shiva Sutra #81:
** video 1
   > Name: Merging & From Thinking to Feeling - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/5tZFUsf-3j4
   > Note: Same as video 1 of 'SS #82'
   > Note: satsang by Nithyananda

** video 2
   > Name: Going from Words to Wordlessness
   > Link: https://youtu.be/dPko9iXUjqQ?si=iKxFim7Dj7KM8Q15
   > Note: 'SS#81' mentioned around min 19:40
   > Note: satsang by Nithyananda

* Shiva Sutra #82:
** video 1
   > Name: Merging & From Thinking to Feeling - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/5tZFUsf-3j4 
   > Note: Same as video 1 of 'SS #81'
         : Starting at (1:27:50)
   > Note: satsang by Nithyananda

* Shiva Sutra #83:

If these videos are beeing watched to study, then they should follow an order (they are refered as A B C intead of 1 2 3 because Z is the last letter, Numbers do no have Last number, so alphabet Z is best to describe the goal)  where Z are videos that show how other people got to the point, understood and experienced

** video A
   > Name: Shiva Sutras Discover who you are
   > Link: https://youtu.be/QTtstf9rdxQ
   > Note: satsang by Nithyananda

** video B
   > Name: PAPAJI - Wake up from the dream
   > Link: https://youtu.be/3z2wJhDDBk0?si=DXIe9jV0A-TKm9de
   > Note: satsang by Papaji
   
** video C
   > Name: You ARE Source The Only Video You Need Bentinho Massaro Greek subs
   > Link: https://youtu.be/1-hJZ8YheTI?si=ta-16tetHZ3nIrV- 
   > Note: satsang by Bentinho Massaro

** video Z
   > Name: Papaji - Spiritual awakening in four minutes
   > Link: https://youtu.be/NMHcak07pmE?si=mebY3rfhD3QMHQcJ
   > Note: satsang by Papaji

* Shiva Sutra #86:
** video 1
   > Name: Perception Beyond Perception - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/Fmgx9m7ISlo
   > Note: Video full of questions until min (29:30)
   > Note: satsang by Nithyananda
 
* Shiva Sutra #87:
** video 1
   > Name: Perception Beyond Perception - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/Fmgx9m7ISlo
   > Note: Same video as 'SS #86' video 1
         : Starting point for 'SS #87' at (1:11:20)
   > Note: satsang by Nithyananda

* Shiva Sutra #89:
** video 1
   > Name: From Known to Knowing - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/0iRBEgdARMo
   > Note: This video includes sutra 'SS #90' at (1:18:30) 
   > Note: satsang by Nithyananda
   > Note: Explains Jesus Imaculate Conception

** video 2
   > Name: Wake Up! & Be Intense
   > Link: https://youtu.be/mgHgTAZhCqg

* Shiva Sutra #90:
** video 1
   > Name: From Known to Knowing - Shiva Sutras in Nithyananda Videos
   > Link: https://youtu.be/0iRBEgdARMo 
   > Note: In the video, the sutra 'SS #90' starts at (1:18:30)
   > Note: satsang by Nithyananda
   > Note: Explains Jesus Imaculate Conception
 
* Shiva Sutra #91:
** video 1
   > Name: Experience Through Your Eyes - Shiva Sutras from Nithyananda Videos
   > Link: https://youtu.be/61Qx0wpsdTA"
   > Note: - Sutra: mentions the sutra 'SS #91' at:
   > Note: - Sutra: mentions the sutra 'SS #92' at:
   > Note: - Sutra: same video as Shiva Sutra #92 video 1: 
   > Note: satsang by Nithyananda
 
* Shiva Sutra #92:
** video 1
   > Name: Experience Through Your Eyes - Shiva Sutras from Nithyananda Videos
   > Link: https://youtu.be/61Qx0wpsdTA
   > Note: Same video as Shiva Sutra #91 video 1: 
         : Starting point: 1:15:50
   > Note: satsang by Nithyananda
 
* Shiva Sutra #94:
** video 1
   > Name: You Are Also Part of 'THAT ESSENCE' - Dhyana Sutra
   > Link: https://youtu.be/V9hHgEeJh7Y
   > Note: 

** video 2
   > Name: Shake the Roots of Negativity of Mind
   > Link: https://youtu.be/EtiCCuLu89Q
   > Note: 

* Misterio?
Satsang about Nithyananda
Name: Add Life to your years
Discourse titled: "Devotion Path to Enlightenment" (San Diego Californa 2007)
Link: https://youtu.be/SBbUlgb8Axk (sutra not mentioned)
Content: - "Maturity means: The hability to face the reality as it is without any buffer springs (car suspention to reduce road shocks)"

* Shiva Sutra #92:
** video 1
   > Part 1: Name: Move Towards Love || Part 1 || Shiva Sutras || 25 May 2007
            Link: https://youtu.be/0o18kpOXEok
            Mencionado 'SS #92' at 00:30
            Conteudo: Destruction from shiva can be seen as "creating space for new things to happen"

   falta ouvir:
   > Part 2: Name: Move Towards Love || Part 2 || Shiva Sutras || 25 May 2007
             Link: https://youtu.be/H8HjL9qKtc4
   > Part 3: Name: Move Towards Love || Part 3 || Shiva Sutras || 25 May 2007
             Link: https://youtu.be/OZtLmn0jmJI
   > Part 4: Name: Move Towards Love || Part 4 || Shiva Sutras || 25 May 2007
             Link: https://youtu.be/A2jnpAXlF2k

** video 2
   > Part 1: Name: Mangalatva - Whatever that is happening is Auspicious
           : Link: https://youtu.be/UnyjwJLNzhI
   > Part 2: Name: Shiva - The Causeless Auspicious Energy
           : Link: and https://youtu.be/RHjOBFAC4H0 (NN *1)
   > Part 3: Name: Inner Space of Shiva 
           : Link: https://youtu.be/bZ2A6y0QBSk
   > Part 4: Name: Reclaim Your Inner Space
           : Link: https://youtu.be/OhBXNg3GzTo (NN *2)"
   > Note: satsang by Nithyananda

* Shiva Sutra #109
** Vide 1
   > Name: PAPAJI - You are Emptyness Itself
   > Link: https://youtu.be/CE33czxSSVg?si=EXi0GLbjlPwOz7pF
   > Note: satsang by Papaji

* Shiva Sutra #110:
** video 1
   > Name: Secret of Time & Anti-ageing | Nithyananda Satsang | 31 Aug 2010
   > Link: https://youtu.be/q7vemMPAQOY
   > Note: In this video Nithyananda does not mention the sutra
         : but he mentions Kala Bhairava and teaches
         : how to play. Kala Bhairava is well explained.
   > Note: satsang by Nithyananda

** video 2
   > Name: Story of Markandeya & Shiva: Who Froze Time | Time & Space | Sadhguru | Adiyogi
   > Link: https://youtu.be/L-Ba_hVNkTs
   > Note: Sadhguru explains the story of Markandeya
         : who Nithyananda mentions in the previous video
         : that escaped the rope of yama
         : by Sadhguru

* Upanishad
** video n
   > Part 1: Name: Present Moment - Keys to Enlightenment Part 1
           : Link: https://youtu.be/3F_nOs01peA
           : Note: - Video is about upanishad
                 : -
   > Part 2: Name: Present Moment - Key to Enlightenment - Part 2
           : Link: https://youtu.be/LJrBhAgVY6A
           : Note: - Sutra:
                 : - Does not mention the sutra
                 : - About TPS (Thoughts per second)

* Default text 

uDev: atender tambem ao modelo usado no 'SS #37'

** Version 1

Shiva Sutra #n:
 - video n -------------------------------
   > Name: 
   > Link: 
   > Note: - Sutra: 
         : - 

** Version 2
Shiva Sutra #n:
 - video n ------------------------------ 
   > Part 1: Name: 
           : Link: 
           : Note: - Sutra: 
                 : -
   > Part 2: Name: 
           : Link: 
           : Note: - Sutra: 
                 : - 
   > Part 3: Name: 
           : Link: 
           : Note: - Sutra: 
                 : -
   > Part 4: Name: 
           : Link: 
           : Note: - Sutra: 
                 : - 
   > Part 5: Name: 
           : Link: 
           : Note: - Sutra: 
                 : - 
   > Part 6: Name: 
           : Link: 
           : Note: - Sutra: 
                 : - 
   > Part 7: Name: 
           : Link: 
           : Note: - Sutra: 
                 : - 
   > Part 8: Name: 
           : Link: 
           : Note: - Sutra: 
                 : - 
   > Part 9: Name: 
           : Link: 
           : Note: - Sutra: 
                 : - 
   > Notes : 

===================================================
 
Shiva Sutras vs Vedanta - Short Nithyananda Videos
SS (no sutra) https://youtu.be/jwJYGsfcIdA (NN *1)

NOTE: Big list of nithyananda videos about shiva sutras: https://nithyananda.tv/playlist/shiva-sutras/
About worshiping GOD in the form of Deity: https://www.youtube.com/shorts/9XxMJ2nRNOQ

